name: CI-beta

on:
  workflow_dispatch:

jobs:
  test-beta:
    name: Test-beta
    runs-on: ubuntu-latest

    environment: develop

    env:
      PYTHON_VERSION: "3.13"

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup UV
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        env:
          TB_BDUSS: ${{ secrets.BDUSS }}
          TB_STOKEN: ${{ secrets.STOKEN }}
        run: |
          uv run pytest
